name=input('Enter Name: ')
print(name,'\n')
LStp_name=name.lstrip( '   Abdul')
RStp_name=name.rstrip( ' Chishti')
Stp_name=name.strip( ' Abdul Chishti')
print('Lstripped Name:')
print(LStp_name,'\n')
print('Rstripped Name:')
print(RStp_name,'\n')
print('Stripped Name:')
print(Stp_name,'\n')
